/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * LarpexAPI
 * OpenAPI spec version: v1
 */
import { customInstance } from './axios-instance';
export type PostPaymentsConfirmPaymentIdParams = {
success?: string;
};

export type PostPaymentsInitParams = {
eventId?: string;
};

export type GetAuthParams = {
email?: string;
};

export interface UpdateEventSettingsResponse {
  eventSettings?: EventSettingsDTO;
}

export interface UpdateEventSettingsRequest {
  eventSettings?: EventSettingsDTO;
}

export interface UpdateEventDTO {
  clientDescription?: string | null;
  currentlySignedPlayers?: number | null;
  employeeDescription?: string | null;
  endDate?: string | null;
  eventStatus?: string | null;
  name?: string | null;
  pricePerUser?: number | null;
  startDate?: string | null;
}

export interface UpdateEventRequest {
  event?: UpdateEventDTO;
}

export interface ReadEventResponse {
  event?: EventDTO;
}

export interface PaymentStatusResponse {
  status?: string | null;
}

export interface InitPayResponse {
  paymentId?: string;
  paymentPrice?: number;
}

export type EventStatus = typeof EventStatus[keyof typeof EventStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;

export interface EventSettingsDTO {
  isExternalOrganiser?: boolean | null;
  isVisible?: boolean | null;
  maxPlayerLimit?: number | null;
}

export interface EventDTO {
  currentlySignedPlayers?: number | null;
  descriptionForClient?: string | null;
  descriptionForEmployee?: string | null;
  endDate?: string;
  eventPrice?: number;
  eventSettings?: EventSettingsDTO;
  eventStatus?: string | null;
  game?: string;
  id?: string | null;
  location?: string;
  name?: string | null;
  ownerEmail?: string | null;
  pricePerUser?: number;
  startDate?: string;
}

export interface UpdateEventResponse {
  event?: EventDTO;
}

export interface GetEventsResponse {
  events?: EventDTO[] | null;
}

export interface CreateTransactionResponse {
  redirectUrl?: string | null;
}

export interface CreateTransactionRequest {
  method?: string | null;
  paymentId?: string;
}

export interface CreateEventResponse {
  event?: EventDTO;
}

export interface CreateEventDTO {
  clientDescription?: string | null;
  currentlySignedPlayers?: number | null;
  employeeDescription?: string | null;
  endDate?: string;
  game?: string;
  location?: string;
  name?: string | null;
  pricePerUser?: number;
  startDate?: string;
}

export interface CreateEventRequest {
  event?: CreateEventDTO;
  eventSettings?: EventSettingsDTO;
}




// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;


  export const getAuth = (
    params?: GetAuthParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/Auth`, method: 'get',
        params
    },
      options);
    }
  
export const getEventsInternalEmployee = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetEventsResponse>(
      {url: `/EventsInternalEmployee`, method: 'get'
    },
      options);
    }
  
export const getEventsInternalEmployeeStatusStatus = (
    status: EventStatus,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetEventsResponse>(
      {url: `/EventsInternalEmployee/status/${status}`, method: 'get'
    },
      options);
    }
  
export const getEventsInternalEmployeeEmailOwnerEmail = (
    ownerEmail: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetEventsResponse>(
      {url: `/EventsInternalEmployee/email/${ownerEmail}`, method: 'get'
    },
      options);
    }
  
export const getEventsInternalOrganiser = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetEventsResponse>(
      {url: `/EventsInternalOrganiser`, method: 'get'
    },
      options);
    }
  
export const postEventsInternalOrganiser = (
    createEventRequest: CreateEventRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<CreateEventResponse>(
      {url: `/EventsInternalOrganiser`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: createEventRequest
    },
      options);
    }
  
export const getEventsInternalOrganiserEventId = (
    eventId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<ReadEventResponse>(
      {url: `/EventsInternalOrganiser/${eventId}`, method: 'get'
    },
      options);
    }
  
export const putEventsInternalOrganiserEventId = (
    eventId: string,
    updateEventRequest: UpdateEventRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<UpdateEventResponse>(
      {url: `/EventsInternalOrganiser/${eventId}`, method: 'put',
      headers: {'Content-Type': 'application/json', },
      data: updateEventRequest
    },
      options);
    }
  
export const deleteEventsInternalOrganiserEventId = (
    eventId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/EventsInternalOrganiser/${eventId}`, method: 'delete'
    },
      options);
    }
  
export const putEventsInternalOrganiserSettingsEventId = (
    eventId: string,
    updateEventSettingsRequest: UpdateEventSettingsRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<UpdateEventSettingsResponse>(
      {url: `/EventsInternalOrganiser/settings/${eventId}`, method: 'put',
      headers: {'Content-Type': 'application/json', },
      data: updateEventSettingsRequest
    },
      options);
    }
  
export const postPaymentsInit = (
    params?: PostPaymentsInitParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<InitPayResponse>(
      {url: `/Payments/init`, method: 'post',
        params
    },
      options);
    }
  
export const postPaymentsCreateTransaction = (
    createTransactionRequest: CreateTransactionRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<CreateTransactionResponse>(
      {url: `/Payments/create-transaction`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: createTransactionRequest
    },
      options);
    }
  
export const postPaymentsConfirmPaymentId = (
    paymentId: string,
    params?: PostPaymentsConfirmPaymentIdParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/Payments/confirm/${paymentId}`, method: 'post',
        params
    },
      options);
    }
  
export const getPaymentsPaymentId = (
    paymentId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PaymentStatusResponse>(
      {url: `/Payments/${paymentId}`, method: 'get'
    },
      options);
    }
  
export type GetAuthResult = NonNullable<Awaited<ReturnType<typeof getAuth>>>
export type GetEventsInternalEmployeeResult = NonNullable<Awaited<ReturnType<typeof getEventsInternalEmployee>>>
export type GetEventsInternalEmployeeStatusStatusResult = NonNullable<Awaited<ReturnType<typeof getEventsInternalEmployeeStatusStatus>>>
export type GetEventsInternalEmployeeEmailOwnerEmailResult = NonNullable<Awaited<ReturnType<typeof getEventsInternalEmployeeEmailOwnerEmail>>>
export type GetEventsInternalOrganiserResult = NonNullable<Awaited<ReturnType<typeof getEventsInternalOrganiser>>>
export type PostEventsInternalOrganiserResult = NonNullable<Awaited<ReturnType<typeof postEventsInternalOrganiser>>>
export type GetEventsInternalOrganiserEventIdResult = NonNullable<Awaited<ReturnType<typeof getEventsInternalOrganiserEventId>>>
export type PutEventsInternalOrganiserEventIdResult = NonNullable<Awaited<ReturnType<typeof putEventsInternalOrganiserEventId>>>
export type DeleteEventsInternalOrganiserEventIdResult = NonNullable<Awaited<ReturnType<typeof deleteEventsInternalOrganiserEventId>>>
export type PutEventsInternalOrganiserSettingsEventIdResult = NonNullable<Awaited<ReturnType<typeof putEventsInternalOrganiserSettingsEventId>>>
export type PostPaymentsInitResult = NonNullable<Awaited<ReturnType<typeof postPaymentsInit>>>
export type PostPaymentsCreateTransactionResult = NonNullable<Awaited<ReturnType<typeof postPaymentsCreateTransaction>>>
export type PostPaymentsConfirmPaymentIdResult = NonNullable<Awaited<ReturnType<typeof postPaymentsConfirmPaymentId>>>
export type GetPaymentsPaymentIdResult = NonNullable<Awaited<ReturnType<typeof getPaymentsPaymentId>>>
