export const apiUrl = "https://larpex-api-gateway.azurewebsites.net/";
export const validJWT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhQGFhLmNvbSIsIm5iZiI6MTcwMjMyMTY0NCwiZXhwIjoxNzAyMzI1MjQ0LCJpYXQiOjE3MDIzMjE2NDQsImlzcyI6IkxhcnBleEFwcCJ9.0JZBXB1qNf7ljLSnNebyxcnTrk3000LIiPjJ1jG6Ex0";
