export const apiUrl = "https://larpex-api-gateway.azurewebsites.net/";
export const validJWT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVrLnN1cnZpdm9yQGV4YW1wbGUuY29tIiwibmJmIjoxNzAxMTkzMjMwLCJleHAiOjE3MDExOTY4MzAsImlhdCI6MTcwMTE5MzIzMCwiaXNzIjoiTGFycGV4QXBwIn0.WUtIWYOzn7tDDgo8mqz2SNP-4CsEYerNfixIoWGFNEk";
